alias cob="git checkout -b "
alias com="git checkout master"
alias gap="git add -p"
alias gc="killall gpg-agent && gpg-agent --daemon --pinentry-program /usr/local/bin/pinentry && git commit -v"
alias gp="git pull"
alias gps="git push -u origin head"
alias gs="git status"
alias gundo="git reset --soft HEAD~1"
alias n=fnm
alias nvm=fnm
